-- PadelStats / Supabase schema
-- À exécuter dans l'éditeur SQL Supabase

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  start_rating numeric(4,2),
  current_rating numeric(4,2),
  delta numeric(4,2) not null default 0.03,
  loss_delta numeric(4,2) not null default 0.05,
  level_defined boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  result text not null check (result in ('win', 'loss')),
  court text not null,
  match_date date not null,
  cost numeric(8,2) not null default 0,
  notes text,
  before_rating numeric(4,2) not null,
  after_rating numeric(4,2) not null,
  rating_change numeric(4,2) not null,
  created_at timestamptz not null default now()
);

create table if not exists public.accessory_costs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  cost_date date not null,
  amount numeric(8,2) not null check (amount >= 0),
  category text not null default 'Accessoire',
  court text,
  notes text,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.matches enable row level security;
alter table public.accessory_costs enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
drop policy if exists "profiles_insert_own" on public.profiles;
drop policy if exists "profiles_update_own" on public.profiles;
drop policy if exists "matches_select_own" on public.matches;
drop policy if exists "matches_insert_own" on public.matches;
drop policy if exists "matches_update_own" on public.matches;
drop policy if exists "accessory_costs_select_own" on public.accessory_costs;
drop policy if exists "accessory_costs_insert_own" on public.accessory_costs;
drop policy if exists "accessory_costs_update_own" on public.accessory_costs;

create policy "profiles_select_own"
  on public.profiles for select
  using (auth.uid() = id);

create policy "profiles_insert_own"
  on public.profiles for insert
  with check (auth.uid() = id);

create policy "profiles_update_own"
  on public.profiles for update
  using (auth.uid() = id);

create policy "matches_select_own"
  on public.matches for select
  using (auth.uid() = user_id);

create policy "matches_insert_own"
  on public.matches for insert
  with check (auth.uid() = user_id);

create policy "matches_update_own"
  on public.matches for update
  using (auth.uid() = user_id);

create policy "accessory_costs_select_own"
  on public.accessory_costs for select
  using (auth.uid() = user_id);

create policy "accessory_costs_insert_own"
  on public.accessory_costs for insert
  with check (auth.uid() = user_id);

create policy "accessory_costs_update_own"
  on public.accessory_costs for update
  using (auth.uid() = user_id);

create index if not exists matches_user_id_match_date_idx
  on public.matches(user_id, match_date desc, id desc);

create index if not exists accessory_costs_user_id_cost_date_idx
  on public.accessory_costs(user_id, cost_date desc, id desc);
