-- PadelStats / Supabase schema
-- À exécuter dans l'éditeur SQL Supabase

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  start_rating numeric(4,2),
  current_rating numeric(4,2),
  delta numeric(4,2) not null default 0.03,
  loss_delta numeric(4,2) not null default 0.05,
  level_defined boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  result text not null check (result in ('win', 'loss')),
  court text not null,
  match_date date not null,
  cost numeric(8,2) not null default 0,
  notes text,
  before_rating numeric(4,2) not null,
  after_rating numeric(4,2) not null,
  rating_change numeric(4,2) not null,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.matches enable row level security;

create policy if not exists "profiles_select_own"
  on public.profiles for select
  using (auth.uid() = id);

create policy if not exists "profiles_insert_own"
  on public.profiles for insert
  with check (auth.uid() = id);

create policy if not exists "profiles_update_own"
  on public.profiles for update
  using (auth.uid() = id);

create policy if not exists "matches_select_own"
  on public.matches for select
  using (auth.uid() = user_id);

create policy if not exists "matches_insert_own"
  on public.matches for insert
  with check (auth.uid() = user_id);

create policy if not exists "matches_update_own"
  on public.matches for update
  using (auth.uid() = user_id);

create index if not exists matches_user_id_match_date_idx
  on public.matches(user_id, match_date desc, id desc);
